spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg-sst-db?serverTimezone=America/Bogota&useSSL=false&allowPublicKeyRetrieval=true
    username: sgsst_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: America/Bogota